# Generated by Django 3.2.15 on 2022-10-03 12:01

from django.db import migrations
from django.contrib.auth.models import Group


def create_groups(apps, schema_editor):
    Group.objects.get_or_create(name="sales employees")
    Group.objects.get_or_create(name="support employees")


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_groups, migrations.RunPython.noop)
    ]
